format = """
$env_var\
$directory\
$git_branch\
$git_commit\
$git_status\
$status\
$fill\
$git_metrics\
$time
$battery\
$character
"""

[env_var]
style = "bold fg:#7FBBB3"
variable = "SHLVL"
format = "[$env_value ]($style)"

[directory]
style = "bold fg:#A7C080"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold fg:#DBBC7F"
format = '[$branch ]($style)'

[git_commit]
style = "bold fg:#DBBC7F"
format = '[$hash$tag ]($style)'
tag_disabled = false

[git_status]
style = "bold fg:#E69875"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[$all_status$ahead_behind ]($style)'

[status]
style = "bold fg:#E67E80"
format = '[$status ]($style)'
disabled = false

[git_metrics]
added_style = 'green'
deleted_style = 'red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold fg:#83C092"
format = '[♥ $time]($style)'

[[battery.display]]
threshold = 15
style = 'bold fg:#D699B6'

[[battery.display]]
threshold = 30
style = 'bold fg:#D699B6'
