format = """
$env_var\
$directory\
$git_branch\
$git_commit\
$git_status\
$status\
$fill\
$git_metrics\
$cmd_duration\
$time
$battery\
$character
"""

#dd_newline = false

[env_var]
style = "bold fg:#7FBBB3 bg:#2D353B"
variable = "SHLVL"
format = "[$env_value ]($style)"

[directory]
style = "bold fg:#A7C080 bg:#2D353B"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold fg:#DBBC7F bg:#2D353B"
format = '[$branch ]($style)'

[git_commit]
style = "bold fg:#DBBC7F bg:#2D353B"
format = '[$hash$tag ]($style)'
tag_disabled = false

[git_status]
style = "bold fg:#E69875 bg:#2D353B"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[$all_status$ahead_behind ]($style)'

[status]
style = "bold fg:#E67E80 bg:#2D353B"
format = '[$status ]($style)'
disabled = false

[fill]
symbol = ' '
style = "bg:#2D353B"

[git_metrics]
added_style = 'green bg:#2D353B'
deleted_style = 'red bg:#2D353B'
format = '[+$added]($added_style)[/](bg:#2D353B)[-$deleted ]($deleted_style)'
disabled = false
only_nonzero_diffs = true

[cmd_duration]
min_time = 100
show_milliseconds = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold fg:#83C092 bg:#2D353B"
format = '[♥ $time]($style)'

[[battery.display]]
threshold = 15
style = "bold fg:#D699B6 bg:#2D353B"

[[battery.display]]
threshold = 30
style = "bold fg:#D699B6 bg:#2D353B"
