theme = "slick"
scrolling = "reverse"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "%a %F %R"

[[block]]
block = "battery"
interval = 60
format = "{percentage} {time}"
