scrolling = "reverse"

[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"

[[block]]
block = "disk_space"
alert_unit = "GB"
format = " $available "

[[block]]
block = "sound"
step_width = 5
headphones_indicator = true
natural_mapping = true
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "notify"
format = " $icon "
[[block.click]]
button = "right"
action = "show"

[[block]]
block = "time"
interval = 15
format = " $timestamp.datetime(f:'%a %F %R') "

[[block]]
block = "battery"
interval = 60
format = " $percentage $time "
